import sys
from PIL import Image
#pip install Pillow
pathColor = (255, 255, 0)

if len(sys.argv) < 4:
    print("The script requires 3 arguments: the name of the input map image, the path file generated by the program and the name of the output image.")
    sys.exit(1)

if len(sys.argv) >= 7:
    pathColor = (int(sys.argv[4]), int(sys.argv[5]), int(sys.argv[6]))


mapFilename = sys.argv[1]
pathFilename = sys.argv[2]
outputFilename = sys.argv[3]

print("Map filename: " + mapFilename)
print("Path filename: " + pathFilename)
print("Output filename: " + outputFilename)
print("Path color: " + str(pathColor))

map = Image.open(mapFilename)
thickness = min(map.width, map.height) * 0.005
thickness = int(max(thickness, 1.0))
print("Path thickness: " + str(thickness))

path = []
with open(pathFilename, "rt") as pathFile:
    for line in pathFile:
        tokens = line.split()
        path.append((int(tokens[0]) - 1, int(tokens[1]) - 1))   #"- 1" to compensate for the added border

normal = (0,0)
for i in range(0, len(path)):
    if i != len(path) - 1:
        normal = (path[i+1][0] - path[i][0], path[i+1][1] - path[i][1])
    orthogonal = (normal[1], -normal[0])

    def writePath():
        for s in range(1, int(thickness / 2) + 1):
            pos = (path[i][0] + s * orthogonal[0], path[i][1] + s * orthogonal[1])

            if pos[0] >= 0 and pos[0] < map.width and pos[1] >= 0 and pos[1] < map.height:
                map.putpixel(pos, pathColor)

    map.putpixel(path[i], pathColor)
    writePath()
    orthogonal = (-orthogonal[0], -orthogonal[1])
    writePath()
    
map.save(outputFilename)

